//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parso.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Id { get; set; }
        public Nullable<long> CatalogId { get; set; }
        public string BarcodeId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string ThumbPictureUrl { get; set; }
        public string PictureUrl { get; set; }
        public string ProductUrl { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string DiscountDetail { get; set; }
    
        public virtual Catalog Catalog { get; set; }
    }
}
